version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/fiasco-online/deploy/server/fiasco-online/
permissions:
  - object: /home/ubuntu/fiasco-online/deploy/server/fiasco-online
    pattern: "*.sh"
    mode: 777
    type:
      - file
hooks:
  BeforeInstall:
    - location: clear.sh
      timeout: 180
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 180