name: CI

on: 
  push:
    branches:
      - master
  
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependancies
      run: npm install

    - name: Send info message on discord
      run: node .github/workflows/discord
      env:
        WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        GITHUB: ${{ toJson(github) }}
        MESSAGE_TYPE: info

    - name: Test
      run: npm test

    - name: Send success message on discord
      run: node .github/workflows/discord
      env:
        WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        GITHUB: ${{ toJson(github) }}
        MESSAGE_TYPE: test-success
    
    - name: Deploy file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
          --region ap-northeast-2 \
          --application-name fiasco-online-server-deploy-service \
          --deployment-group-name fiasco-online-server-deploy-group \
          --github-location repository="online-fiasco/fiasco-online",commitId="${{ github.sha }}"
    
    - name: Send failure message on discord
      if: failure()
      run: node .github/workflows/discord
      env:
        WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        GITHUB: ${{ toJson(github) }}
        MESSAGE_TYPE: test-failed